name: CI
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - run: echo %GITHUB_ENV%
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
