name: CI
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - run: echo $env:GITHUB_ENV
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
